"use client";

import { useState, useEffect, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeToggle } from "@/components/theme-toggle";
import { Check, Minus, ChevronDown, ChevronUp, CheckCircle2, XCircle } from "lucide-react";
import Link from "next/link";

const plans = [
  {
    id: "starter",
    name: "Starter",
    price: 29,
    videos: 50,
    pricePerVideo: 0.58,
    margin: "96%",
    features: [
      "50 unique creatives per month",
      "Unlimited video combinations",
      "All aspect ratios (9:16, 16:9, 1:1, 4:5)",
      "Custom module structure",
      "Download individual videos",
      "Bulk ZIP download",
      "Email support",
    ],
    notIncluded: [
      "Priority processing",
      "API access",
      "Dedicated support",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    price: 59,
    videos: 200,
    pricePerVideo: 0.30,
    margin: "93%",
    popular: true,
    features: [
      "200 unique creatives per month",
      "Unlimited video combinations",
      "All aspect ratios (9:16, 16:9, 1:1, 4:5)",
      "Custom module structure",
      "Download individual videos",
      "Bulk ZIP download",
      "Priority processing",
      "Priority email support",
    ],
    notIncluded: [
      "API access",
      "Dedicated support",
    ],
  },
  {
    id: "scale",
    name: "Scale",
    price: 199,
    videos: 2000,
    pricePerVideo: 0.10,
    margin: "80%",
    features: [
      "2,000 unique creatives per month",
      "Unlimited video combinations",
      "All aspect ratios (9:16, 16:9, 1:1, 4:5)",
      "Custom module structure",
      "Download individual videos",
      "Bulk ZIP download",
      "Priority processing",
      "API access",
      "Dedicated support",
      "Custom integrations",
    ],
    notIncluded: [],
  },
];

const faqs = [
  {
    question: "What is a Custom Video Matrix?",
    answer: "It's the tool you use to multiply your creative production: you choose the modules (hook, body, CTA, closing, transition, argument, etc.), define how many assets you'll put in each one and the display order; the matrix then automatically combines these assets into all possible variations, generating multiple final videos ready for testing — for example, if you use 3 hooks, 2 bodies, and 2 CTAs, you'll get 12 unique videos (3×2×2=12).",
  },
  {
    question: "What is considered a \"unique creative\"?",
    answer: "It's each creative variation generated by the combination of the matrix you built. If you configure, for example, 3 hooks, 3 bodies, and 3 CTAs, the system can generate 27 different videos (3×3×3=27), and each of these videos counts as a unique creative.",
  },
  {
    question: "How are credits consumed?",
    answer: "Each unique creative consumes credits: minimum of 1 credit per creative. Duration is rounded up in 5-minute blocks and we charge 1 credit per each 5-min block (e.g.: up to 5 min = 1 credit; 5–10 min = 2; and so on).",
  },
  {
    question: "Can I upgrade or downgrade my plan?",
    answer: "You can change your plan at any time. When upgrading, access to new limits is immediate. On downgrade, changes take effect at the beginning of the next billing cycle.",
  },
  {
    question: "Does HookScale store my videos?",
    answer: "Yes. Each project created is saved within your account, with variations organized by name and tag. You can export, review, and reuse whenever you want.",
  },
];

function PricingContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState<string | null>(null);
  const [showSuccessMessage, setShowSuccessMessage] = useState(false);
  const [showCanceledMessage, setShowCanceledMessage] = useState(false);
  const [user, setUser] = useState<any>(null);
  const [currentSubscription, setCurrentSubscription] = useState<any>(null);
  const [checkingAuth, setCheckingAuth] = useState(true);

  useEffect(() => {
    checkAuth();
  }, []);

  useEffect(() => {
    const success = searchParams.get("success");
    const canceled = searchParams.get("canceled");
    const sessionId = searchParams.get("session_id");

    if (success === "true" && sessionId) {
      router.push(`/pricing/success?session_id=${sessionId}`);
    } else if (canceled === "true") {
      setShowCanceledMessage(true);
      setTimeout(() => setShowCanceledMessage(false), 5000);
    }
  }, [searchParams, router]);

  const checkAuth = async () => {
    try {
      const userStr = localStorage.getItem("user");
      if (userStr) {
        const userData = JSON.parse(userStr);
        setUser(userData);

        // Check current subscription
        const response = await fetch(`/api/check-subscription?customer_id=${userData.id}`);
        const data = await response.json();

        if (data.hasSubscription) {
          setCurrentSubscription(data.subscription);
        }
      }
    } catch (error) {
      console.error("Auth check error:", error);
    } finally {
      setCheckingAuth(false);
    }
  };

  const handleCheckout = async (planId: string) => {
    // Check if user is trying to subscribe to same plan
    if (currentSubscription && currentSubscription.planId === planId) {
      alert("You're already subscribed to this plan");
      return;
    }

    setIsLoading(planId);
    
    try {
      const response = await fetch("/api/create-checkout-session", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          planId,
          userId: user?.id,
          isUpgrade: currentSubscription ? isUpgrade(currentSubscription.planId, planId) : false,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to create checkout session");
      }

      const { url } = await response.json();
      window.location.href = url;
    } catch (error) {
      console.error("Checkout error:", error);
      alert("Failed to start checkout. Please try again.");
      setIsLoading(null);
    }
  };

  const isUpgrade = (currentPlan: string, newPlan: string) => {
    const planOrder = { starter: 1, premium: 2, scale: 3 };
    return planOrder[newPlan as keyof typeof planOrder] > planOrder[currentPlan as keyof typeof planOrder];
  };

  const getButtonText = (planId: string) => {
    if (isLoading === planId) return "Loading...";
    if (!user) return "Get Started";
    if (currentSubscription?.planId === planId) return "Current Plan";
    if (currentSubscription) {
      return isUpgrade(currentSubscription.planId, planId) ? "Upgrade" : "Downgrade";
    }
    return "Subscribe";
  };

  const isCurrentPlan = (planId: string) => {
    return currentSubscription?.planId === planId;
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-foreground/10">
        <div className="container mx-auto flex items-center justify-between px-4 py-4">
          <Link href="/">
            <h1 className="text-xl font-semibold cursor-pointer hover:opacity-80 transition-opacity">
              <span className="text-foreground">Hook</span>
              <span className="text-green-500">Scale</span>
              <span className="text-foreground/40 text-sm font-normal">.ai</span>
            </h1>
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/">
              <Button variant="ghost" className="text-foreground/60 hover:text-foreground">
                Back to App
              </Button>
            </Link>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-7xl">
        {/* Canceled Message */}
        {showCanceledMessage && (
          <div className="mb-8 p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-lg flex items-center gap-3 max-w-2xl mx-auto">
            <XCircle className="w-5 h-5 text-yellow-500 flex-shrink-0" />
            <p className="text-sm">
              Checkout was canceled. No charges were made. Feel free to try again when you're ready.
            </p>
          </div>
        )}

        {/* Hero Section */}
        <div className="text-center mb-16">
          <Badge className="mb-4 bg-green-500/10 text-green-500 border-green-500/20">
            Simple, Transparent Pricing
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            Scale Your Creative Production
          </h1>
          <p className="text-lg text-foreground/60 max-w-2xl mx-auto">
            Choose the plan that fits your needs. All plans include unlimited combinations
            and all features. Pay only for the creatives you generate.
          </p>
        </div>

        {/* Pricing Cards */}
        <div className="grid md:grid-cols-3 gap-8 mb-24">
          {plans.map((plan) => (
            <Card
              key={plan.id}
              className={`relative p-6 ${
                plan.popular
                  ? "border-green-500 shadow-lg shadow-green-500/20 scale-105"
                  : "border-foreground/10"
              }`}
            >
              {plan.popular && (
                <Badge className="absolute -top-3 left-1/2 -translate-x-1/2 bg-green-500 text-white">
                  Most Popular
                </Badge>
              )}

              <div className="text-center mb-6">
                <h3 className="text-2xl font-bold mb-2">{plan.name}</h3>
                <div className="flex items-baseline justify-center gap-1">
                  <span className="text-4xl font-bold">${plan.price}</span>
                  <span className="text-foreground/50">/month</span>
                </div>
                <p className="text-sm text-foreground/60 mt-2">
                  {plan.videos} creatives • ${plan.pricePerVideo}/creative
                </p>
              </div>

              <Button
                onClick={() => handleCheckout(plan.id)}
                disabled={isLoading !== null || isCurrentPlan(plan.id)}
                className={`w-full mb-6 ${
                  isCurrentPlan(plan.id)
                    ? "bg-foreground/10 text-foreground/40 cursor-not-allowed"
                    : plan.popular
                    ? "bg-green-500 hover:bg-green-600 text-white"
                    : "bg-foreground/10 hover:bg-foreground/20"
                }`}
              >
                {getButtonText(plan.id)}
              </Button>

              <div className="space-y-3">
                {plan.features.map((feature, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <Check className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-sm">{feature}</span>
                  </div>
                ))}
                {plan.notIncluded.map((feature, i) => (
                  <div key={i} className="flex items-start gap-2 opacity-40">
                    <Minus className="w-5 h-5 flex-shrink-0 mt-0.5" />
                    <span className="text-sm">{feature}</span>
                  </div>
                ))}
              </div>
            </Card>
          ))}
        </div>

        {/* FAQ Section */}
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-foreground/60">
              Everything you need to know about HookScale
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <Card
                key={index}
                className="border-foreground/10 overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === index ? null : index)}
                  className="w-full p-6 text-left flex items-start justify-between gap-4 hover:bg-foreground/5 transition-colors"
                >
                  <div className="flex-1">
                    <h3 className="font-semibold text-lg mb-1">{faq.question}</h3>
                    {openFaq === index && (
                      <p className="text-foreground/60 mt-3 leading-relaxed">
                        {faq.answer}
                      </p>
                    )}
                  </div>
                  {openFaq === index ? (
                    <ChevronUp className="w-5 h-5 text-foreground/40 flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-foreground/40 flex-shrink-0" />
                  )}
                </button>
              </Card>
            ))}
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center mt-24 p-12 rounded-2xl bg-gradient-to-br from-green-500/10 to-green-500/5 border border-green-500/20">
          <h2 className="text-3xl font-bold mb-4">
            Ready to scale your creative production?
          </h2>
          <p className="text-foreground/60 mb-8 max-w-2xl mx-auto">
            Join hundreds of marketers who are already using HookScale to generate
            thousands of video variations and find winning creatives faster.
          </p>
          <Link href="/">
            <Button className="bg-green-500 hover:bg-green-600 text-white px-8 py-6 text-lg">
              Start Creating Videos
            </Button>
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-foreground/10 mt-24">
        <div className="container mx-auto px-4 py-8 text-center text-sm text-foreground/50">
          <p>© 2026 HookScale. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

export default function PricingPage() {
  return (
    <Suspense fallback={<div className="min-h-screen bg-background flex items-center justify-center">Loading...</div>}>
      <PricingContent />
    </Suspense>
  );
}
